#!/bin/bash

# Train ML Models on Custom JSON File
# Trains admission controller ML models using any specified JSON log file

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
INPUT_FILE="$1"

if [ -z "$INPUT_FILE" ]; then
    echo "ERROR: No input file specified"
    exit 1
fi

echo "Training ML models on custom data..."

# Train the ML model
echo "Training ML model..."
cd "$PROJECT_DIR"
python3 analysis/admission_controller_ml.py train-from-json --input "$INPUT_FILE"

# Verify outputs are created
echo "Verifying model outputs..."
if [ ! -f "./test-results/ml_admission_controller_ident.pkl" ]; then
    echo "ERROR: Model file not created"
    exit 1
fi

if [ ! -f "./test-results/ml_admission_controller_ident.db" ]; then
    echo "ERROR: Database file not created"
    exit 1
fi

echo "Model and database created successfully"

# Report already generated by training process with timestamp
echo "Activity training report generated: ./test-results/activity_report_[timestamp].txt"

echo "Training completed successfully"